name: lifesync_capstone_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png
    - assets/images/logo_paud.png
    - assets/images/logo_ortu.png
    - assets/images/logo_guru.png
    - assets/images/photo1.png
    - assets/images/photo2.png
    - assets/images/placeholder_slider.jpg
    - assets/images/placeholder_updates.jpg
    - assets/images/lh_cover.png
    - assets/images/lm_cover.png
    - assets/images/ls_cover.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

# ⬇️ Konfigurasi splash screen diletakkan DI SINI, setelah flutter:
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen.png
  # branding: assets/images/branding.png
  android: true
  ios: true
