name: lifesync_capstone_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_core: ^3.13.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  supabase_flutter: ^2.0.0
  dio: ^5.4.0
  path_provider: ^2.1.1
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png
    - assets/images/logo_paud.png
    - assets/images/logo_ortu.png
    - assets/images/logo_guru.png
    - assets/images/photo1.png
    - assets/images/photo2.png
    - assets/images/placeholder_slider.jpg
    - assets/images/placeholder_updates.png
    - assets/images/lh_cover.png
    - assets/images/lm_cover.png
    - assets/images/ls_cover.png
    - assets/images/laporan_img.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

# ⬇️ Konfigurasi splash screen diletakkan DI SINI, setelah flutter:
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen.png
  # branding: assets/images/branding.png
  android: true
  ios: true
