name: lifesync_capstone_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png
    - assets/images/logo_paud.png
    - assets/images/logo_ortu.png
    - assets/images/logo_guru.png

# ⬇️ Konfigurasi splash screen diletakkan DI SINI, setelah flutter:
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen.png
  # branding: assets/images/branding.png
  android: true
  ios: true
