// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWi487V3M7eFlzwISErxthNWOMB9jjTkY',
    appId: '1:572728267771:web:68f7070bba69824b47715e',
    messagingSenderId: '572728267771',
    projectId: 'lifesync-capstone',
    authDomain: 'lifesync-capstone.firebaseapp.com',
    databaseURL: 'https://lifesync-capstone-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lifesync-capstone.firebasestorage.app',
    measurementId: 'G-ZSWTY5ZXHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMclDLV2IMs6x_vyXa4LysE88JvUCC6W0',
    appId: '1:572728267771:android:486bc1712e76cb6f47715e',
    messagingSenderId: '572728267771',
    projectId: 'lifesync-capstone',
    databaseURL: 'https://lifesync-capstone-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lifesync-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd7BcLJb1InG3NFKnHqL1YGOjCjnjcGHk',
    appId: '1:572728267771:ios:f281ad1acd06add647715e',
    messagingSenderId: '572728267771',
    projectId: 'lifesync-capstone',
    databaseURL: 'https://lifesync-capstone-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lifesync-capstone.firebasestorage.app',
    iosBundleId: 'com.example.lifesyncCapstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd7BcLJb1InG3NFKnHqL1YGOjCjnjcGHk',
    appId: '1:572728267771:ios:f281ad1acd06add647715e',
    messagingSenderId: '572728267771',
    projectId: 'lifesync-capstone',
    databaseURL: 'https://lifesync-capstone-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lifesync-capstone.firebasestorage.app',
    iosBundleId: 'com.example.lifesyncCapstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWi487V3M7eFlzwISErxthNWOMB9jjTkY',
    appId: '1:572728267771:web:d8a1bfec723e52d247715e',
    messagingSenderId: '572728267771',
    projectId: 'lifesync-capstone',
    authDomain: 'lifesync-capstone.firebaseapp.com',
    databaseURL: 'https://lifesync-capstone-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lifesync-capstone.firebasestorage.app',
    measurementId: 'G-8WWVQY6KZ1',
  );

}